### ISSUE TITLE
Provide prebuild artifacts as tar.gz instead .zip

### ISSUE THREAD

**Issue by jkroepke** [nikhilsbhat/helm-images#1]
helm plugin install has the ability to install plugin from git OR from URL (.tar.gz) files

https://github.com/helm/helm/blob/657850e44b880cca43d0606ebf5a54eb75362c3f/pkg/plugin/installer/http_installer.go#L57-L72

Sometimes, git is not available and 

```
helm plugin install https://github.com/nikhilsbhat/helm-images/releases/download/v0.0.5/helm-images_0.0.5_Linux_x86_64.tar.gz
```

could work here, if available.

**Comment by nikhilsbhat** [comment]
required changes was done to support this and [latest](https://github.com/nikhilsbhat/helm-images/releases/tag/v0.0.6) release supports this
