### ISSUE TITLE
cert-manager-acmesolver image not found by helm image plugin

### ISSUE THREAD

**Issue by dirkvdplas** [nikhilsbhat/helm-images#11]
The cert-manager chart contains cert-manager-acmesolver which is not deployed immediately upon chart installation. Helm images plugin does not list it. Is this expected? Is this an bug with helm images plugin or with the helm chart (cert-manager). Any workaround?

Below the output  in order to reproduce:

helm repo add jetstack https://charts.jetstack.io
helm repo update
helm pull jetstack/cert-manager

The values.yaml contains:
acmesolver:
  image:
    repository: quay.io/jetstack/cert-manager-acmesolver

However this image is not listed:

helm images get cert-manager cert-manager-v1.12.3.tgz -f cert-manager/values.yaml --unique
quay.io/jetstack/cert-manager-cainjector:v1.12.3
quay.io/jetstack/cert-manager-controller:v1.12.3
quay.io/jetstack/cert-manager-webhook:v1.12.3
quay.io/jetstack/cert-manager-ctl:v1.12.3

**Comment by nikhilsbhat** [comment]
Hey @dirkvdplas,

If the image references are being used in any of the workloads that the plugin supports, then the plugin should definitely list them.
The supported workloads can be found under the flag '**--kind**' of the output '**helm images get --help'**.
If the image '**quay.io/jetstack/cert-manager-acmesolver**' is not being used under any of the workloads the plugin supports, then yes, the plugin would not list them.

I have not tested the plugin by reproducing the scenario yet. I'll do the same and update again.

**Comment by nikhilsbhat** [comment]
Hey @dirkvdplas 

As I mentioned earlier, the image '**quay.io/jetstack/cert-manager-acmesolver**' mentioned under **acmesolver.image** is not being used by any of the Kubernetes workloads; rather, it is passed as an arg to the container, and hence the plugin would not identify it.

The plugin is designed to work this way.
