### ISSUE TITLE
Would like to ignore helm tests, please add --skip-tests and --skip-crds

### ISSUE THREAD

**Issue by Eric-Fontana-Indico** [nikhilsbhat/helm-images#18]
Would be nice to be able to ignore the test images and/or CRDs

**Comment by nikhilsbhat** [comment]
Hey @Eric-Fontana-Indico , the [commit](https://github.com/nikhilsbhat/helm-images/commit/e98c10a28b8ce7e42a3f110114e50e6b7db0c7f0) has the necessary changes. The upcoming release would have these changes.

**Comment by nikhilsbhat** [comment]
newer version with support is released, closing this.
