### ISSUE TITLE
Get images from chart registry

### ISSUE THREAD

**Issue by hawksight** [nikhilsbhat/helm-images#20]
I've been thinking about writing something that does exactly what your plugin does. Thank you for making it open.

It seems to me that I have to either have a chart locally or have it installed to get the images.

Is there a way to get the images from a chart that is not installed. My use case is that before I install a chart, I may need to get a list of all images the chart uses and pull those into my own registry. My cluster may not let me install from public, so in this case I would not have a release in cluster to get the images from.

I was looking for something like:

```shell
helm images get oci://my-repo/charts/my-chart
```

Where the `[RELEASE]` is not required as part of the command.

**Comment by nikhilsbhat** [comment]
@hawksight, It is great to hear that you find this plugin useful.

Since the plugin uses `helm template` in the process of identifying images, fetching images from the registry should work; I meant the command `helm images get airflow oci://registry-1.docker.io/bitnamicharts/airflow` should work.
Just that limiting version of the chart is something that the plugin is not supporting now. I'll check that part alone.

**Comment by hawksight** [comment]
@nikhilsbhat thanks for the comment back. I see now it does not have to be installed, simply a valid release name for the `helm template` command. If it doesn't matter what the release name is, it would be nice not to need to pass it in with this plugin.

Eg, you passed `airflow` as the release name, but you could just use a default release name like `example`.

I actually found some command line wizardry using `yq` that actually does the same thing as your plugin, in case you find this useful. ([Source](https://stackoverflow.com/a/64436933))

```shell
helm template . \
    | yq '..|.image? | select(.)' \
    | sort -u
```

**Comment by nikhilsbhat** [comment]
closing this as the latest [release](https://github.com/nikhilsbhat/helm-images/releases/tag/v0.1.2) has the necessary changes.
