### ISSUE TITLE
--no-color should be the default

### ISSUE THREAD

**Issue by jwhitcraft** [nikhilsbhat/helm-images#24]
I was using this plugin in our deployment pipeline and with the latest update the --no-color broke our automation as we didn't know we need to explicitly turn it off since we are piping through `jq`.  IMO by default the color should be off, to where you have to explicitly turn it on.

Just a thought

**Comment by nikhilsbhat** [comment]
@jwhitcraft, it makes sense to turn the colour off by default. I'll do the necessary changes.

**Comment by nikhilsbhat** [comment]
@jwhitcraft, I again thought about not setting the colour by default. The colouring is targeted mainly at the ones who execute it locally. If we turn off the colour by default, it hampers the local execution.

For automations such as your use case, we can still set the flag `--no-color`.

**Comment by jwhitcraft** [comment]
Makes sense, can the readme be updated to show all the options for the command then?  Currently `--no-color` isn't listed there.

**Comment by nikhilsbhat** [comment]
The cli document is updated with all available commands and flags [here](https://github.com/nikhilsbhat/helm-images/blob/master/docs/doc/images_get.md#options)
