### ISSUE TITLE
Getting images fro the JFrog Artifactory helm chart hangs

### ISSUE THREAD

**Issue by ktarplee** [nikhilsbhat/helm-images#36]
```bash
helm repo add jfrog https://charts.jfrog.io
helm repo update

helm images get jfrog/artifactory
```

It hammers the CPU and does not return after a few minutes.

**Comment by nikhilsbhat** [comment]
@ktarplee , I successfully retrieved images from the jfrog/artifactory. Indeed, it took an unusually long time to obtain the results. 
To troubleshoot this, I pulled the Helm charts locally and discovered a large `ConfigMap` named 'sample-artifactory-migration-scripts'. 
Given that the `ConfigMap` is big the plugin's identification of images from this `ConfigMap` appears to be the bottleneck. Consider invoking the plugin while skipping this specific `ConfigMap` to observe the difference in performance.

`helm images get jfrog/artifactory --skip ConfigMap=sample-artifactory-migration-scripts`

**Comment by ktarplee** [comment]
I was not patient enough.  Mine took over a minute when I finally let it run through.  I ran `helm template jfrog/artifactory` and it took only a second to run so I figured something was not working (and this was the first time I used `helm images`).  Thanks for the `--skip` flag.

**Comment by ktarplee** [comment]
The output is 
```txt
releases-docker.jfrog.io/jfrog/nginx-artifactory-pro:7.77.10
releases-docker.jfrog.io/ubi9/ubi-minimal:9.3.1475
releases-docker.jfrog.io/bitnami/postgresql:13.10.0-debian-11-r14
releases-docker.jfrog.io/jfrog/router:7.91.0
releases-docker.jfrog.io/jfrog/artifactory-pro:7.77.10
releases-docker.jfrog.io/jfrog/artifactory-pro:7.77.10
releases-docker.jfrog.io/jfrog/artifactory-pro:7.77.10
releases-docker.jfrog.io/jfrog/artifactory-pro:7.77.10
releases-docker.jfrog.io/jfrog/artifactory-pro:7.77.10
releases-docker.jfrog.io/jfrog/artifactory-pro:7.77.10
releases-docker.jfrog.io/ubi9/ubi-minimal:9.3.1475
releases-docker.jfrog.io/ubi9/ubi-minimal:9.3.1475
releases-docker.jfrog.io/ubi9/ubi-minimal:9.3.1475
releases-docker.jfrog.io/jfrog/artifactory-pro:7.77.10
```
Why does the tool not deduplicate (and sort) the output?

**Comment by nikhilsbhat** [comment]
@ktarplee , plugin does support de-duplication, please check the plugin [docs](https://github.com/nikhilsbhat/helm-images?tab=readme-ov-file#documentation) for all available flags.
