### ISSUE TITLE
Missing images from kube-prom-stack

### ISSUE THREAD

**Issue by kiemlicz** [nikhilsbhat/helm-images#8]
Hello,

Is it possible to get the images from Charts like: `prometheus-community/kube-prometheus-stack` which heavily use CRDs ?
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

By the output of
```
> helm images get --set alertmanager.enabled=true prometheus prometheus-community/kube-prometheus-stack
quay.io/prometheus/node-exporter:v1.5.0
quay.io/kiwigrid/k8s-sidecar:1.22.0
quay.io/kiwigrid/k8s-sidecar:1.22.0
docker.io/grafana/grafana:9.5.1
registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.2
quay.io/prometheus-operator/prometheus-operator:v0.65.1
docker.io/bats/bats:v1.4.1
registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6%      
```
I think that many images are not listed, like alertmanager's

Is it some config issue or unsupported case?

**Comment by nikhilsbhat** [comment]
Hey @kiemlicz,

The plugin supports only the following workloads: Deployment, StatefulSet, DaemonSet, CronJob, Job, ReplicaSet, and Pod. The plugin does not support CRDs currently.
Initially, I tried to make this plugin read from all the resources (including CRDs), which introduced a lot of bugs.
I will try to work on this again to fix it once and for all; if not, I will add support to Promethues [Operator](https://prometheus-operator.dev/docs/operator/api/).

**Comment by nikhilsbhat** [comment]
Hey @kiemlicz,

The [commit](fcf404672a2d52347ab33bc369e09b84c46546db) has the necessary changes to support fetching images from the Prometheus operator.

The changes will be available with the next release.

**Comment by nikhilsbhat** [comment]
Latest [release](https://github.com/nikhilsbhat/helm-images/releases/tag/v0.1.0) supports fetching images from prometheus operator CRD.
